all:
	latex fastcluster.tex
	latex fastcluster.tex
	latex fastcluster.tex
	dvipdfmx fastcluster.dvi
	mkdir keep
	mv fastcluster.pdf keep
	mv fastcluster.tex keep
	rm fastcluster.*
	mv keep/* .
	rmdir keep
